// react/src/pages/Game/components/Players/index.tsx
import React from "react";

import { GameContext } from "#/contexts";

import * as S from "./styled";

const Players: React.FC = () => {
  const { state } = GameContext.useGame();

  const activeUsers = React.useMemo(() => {
    return state?.game?.users?.filter((item) =>
      state.game?.activeUsers?.includes?.(item.id)
    );
  }, [state]);

  const inactiveUsers = React.useMemo(() => {
    return state?.game?.users?.filter(
      (item) => !state.game?.activeUsers?.includes?.(item.id)
    );
  }, [state]);

  return (
    <S.Container>
      <S.Title>Jogadores Ativos</S.Title>

      <S.Players>
        {activeUsers?.map((item) => (
          <S.Player active={item.id === state?.game?.currentUser}>
            {item.name} - {item.time || 0}
          </S.Player>
        ))}
      </S.Players>

      {!inactiveUsers?.length ? null : (
        <>
          <S.Title>Eliminados</S.Title>

          <S.Players>
            {inactiveUsers?.map((item) => (
              <S.Player active={false}>{item.name}</S.Player>
            ))}
          </S.Players>
        </>
      )}
    </S.Container>
  );
};

export default Players;

// angular/src/app/pages/game/components/players/players.component.ts
import {
  Component,
  inject,
  OnChanges,
  OnInit,
  SimpleChanges,
} from '@angular/core';

import { GameService } from '#/app/services/game.service';
import * as GameTypes from 'types/game';
import { Observer, Subscriber } from 'rxjs';

@Component({
  selector: 'page-game-players',
  imports: [],
  templateUrl: './players.component.html',
  styleUrl: './players.component.css',
})
export class PlayersComponent implements OnInit {
  private gameService = inject(GameService);

  currentUser?: number;
  activeUsers: GameTypes.GameUser[] = [];
  inactiveUsers: GameTypes.GameUser[] = [];

  ngOnInit(): void {
    this.processGame(this.gameService.game as GameTypes.Game);

    this.gameService.observerGame().subscribe((result) => {
      const game = result as GameTypes.Game;

      this.processGame(game);
    });
  }

  processGame = (game: GameTypes.Game) => {
    this.currentUser = game.currentUser;

    this.activeUsers = game?.users?.filter((item) =>
      game?.activeUsers?.includes?.(item.id)
    );

    this.inactiveUsers = game?.users?.filter(
      (item) => !game?.activeUsers?.includes?.(item.id)
    );
  };
}

<span id="title">Jogadores ativos</span>

<div id="players">
  @for (player of activeUsers; track player.id) {
  <span class="player" [class.bold]="player.id === currentUser">
    {{ player.name }} - {{ player.time || 0 }}
  </span>
  }
</div>

@if (inactiveUsers.length) {
<span id="title">Eliminados</span>

<div id="players">
  @for (player of inactiveUsers; track player.id) {
  <span class="player">
    {{ player.name }}
  </span>
  }
</div>
}
