// react/src/pages/Game/components/ButtonGame/index.tsx
import React from "react";
import { differenceInMilliseconds } from "date-fns";

import { GameContext } from "#/contexts";

import * as S from "./styled";

const ButtonGame: React.FC = () => {
  const { state, updateGame } = GameContext.useGame();
  const [button, setButton] = React.useState<{ active: boolean; date?: Date }>({
    active: false,
  });

  const showButton = React.useMemo(
    () => state?.game?.currentUser === state?.user,
    [state]
  );

  const handleOnClick = () => {
    const time = differenceInMilliseconds(new Date(), button!.date!);

    updateGame(time);

    setButton({ active: false, date: undefined });
  };

  React.useEffect(() => {
    if (!showButton) return;

    const ramdomTimeout = Math.floor(Math.random() * 2000);

    setTimeout(() => {
      setButton({ active: true, date: new Date() });
    }, ramdomTimeout);
  }, [showButton]);

  return (
    <S.Container>
      {showButton ? (
        <S.Button disabled={!button.active} onClick={handleOnClick}>
          Clique Aqui
        </S.Button>
      ) : (
        <S.Wait>Aguarde sua vez</S.Wait>
      )}
    </S.Container>
  );
};

export default ButtonGame;

// angular/src/app/pages/game/components/button-game/button-game.component.ts
import { Component, inject, OnInit } from '@angular/core';
import { differenceInMilliseconds, isThisMinute } from 'date-fns';

import { GameService } from '#/app/services/game.service';
import * as GameTypes from 'types/game';

@Component({
  selector: 'page-game-button-game',
  imports: [],
  templateUrl: './button-game.component.html',
  styleUrl: './button-game.component.css',
})
export class ButtonGameComponent implements OnInit {
  private gameService = inject(GameService);

  game?: Partial<GameTypes.Game>;
  showButton: boolean = false;
  activeButton: boolean = false;
  date?: Date;

  ngOnInit(): void {
    this.processGame(this.gameService.game as GameTypes.Game);

    this.gameService.observerGame().subscribe((result) => {
      const game = result as GameTypes.Game;
      this.processGame(game);
    });
  }

  processGame = (game: GameTypes.Game) => {
    this.game = game;

    this.showButton = game.currentUser === this.gameService.user;

    if (!this.showButton) return;

    const ramdomTimeout = Math.floor(Math.random() * 2000);

    setTimeout(() => {
      console.log('executou o timeout');

      this.activeButton = true;
      this.date = new Date();
    }, ramdomTimeout);
  };

  handleOnClick = () => {
    if (!this.activeButton) return;

    const time = differenceInMilliseconds(new Date(), this!.date!);

    this.gameService.handleOnUpdateGame(time);

    this.activeButton = false;
    this.date = undefined;
  };
}

@if (showButton) {
<button
  id="button"
  [class.active]="activeButton"
  [class.inactive]="!activeButton"
  (click)="handleOnClick()"
>
  Clique Aqui
</button>
} @else {
<span id="wait"> Aguarde sua vez </span>
}
