// angular/src/app/pages/register/components/waiting-game/waiting-game.component.ts
import { Component, inject } from '@angular/core';

import { GameService } from '#/app/services/game.service';
import * as GameTypes from 'types/game';

import { ButtonComponent } from '../../../../components/button/button.component';

@Component({
  selector: 'page-register-waiting-game',
  imports: [ButtonComponent],
  templateUrl: './waiting-game.component.html',
  styleUrl: './waiting-game.component.css',
})
export class WaitingGameComponent {
  private gameService = inject(GameService);
  game?: Partial<GameTypes.Game>;

  constructor() {
    this.game = this.gameService.game;

    this.gameService.observerGame().subscribe({
      next: (game: any) => {
        this.game = game;
      },
    });
  }

  handleOnStart = () => {
    this.gameService.handleOnStartGame();
  };
}

<span id="title">Aguardando outros jogadores - Sala {{ game?.room }}</span>

<span id="legend">{{ game?.users?.length || 0 }} na sala</span>

<component-button label="Iniciar" (click)="handleOnStart()" />

// react/src/pages/Register/components/WaitingGame/index.tsx
import React from "react";

import { Button } from "#/components";
import { GameContext } from "#/contexts";

import * as S from "./styled";

const UserForm: React.FC = () => {
  const { state, startGame } = GameContext.useGame();

  const handleOnStart = async () => {
    startGame();
  };

  const users = state?.game?.users?.length || 0;
  const room = state?.game?.room;

  return (
    <>
      <S.Title>Aguardando outros jogadores - Sala {room}</S.Title>

      <S.Legend>{users} na sala</S.Legend>

      <Button onClick={handleOnStart}>Iniciar</Button>
    </>
  );
};

export default UserForm;
